:green_heart: :arrow_up: Update pyenv init command in `~/.bashrc`
Fixes:
```
2021-05-23T02:33:27.269Z	INFO	WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
2021-05-23T02:33:27.269Z	ERROR	Downloading Python-3.7.9.tar.xz...
-> https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tar.xz
Installing Python-3.7.9...
Installed Python-3.7.9 to /root/.pyenv/versions/3.7.9
2021-05-23T02:33:27.269Z	INFO	WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
2021-05-23T02:33:27.270Z	ERROR	Downloading Python-3.8.6.tar.xz...
-> https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tar.xz
Installing Python-3.8.6...
Installed Python-3.8.6 to /root/.pyenv/versions/3.8.6
2021-05-23T02:33:27.270Z	INFO	WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
2021-05-23T02:33:27.270Z	ERROR	Downloading Python-3.9.4.tar.xz...
-> https://www.python.org/ftp/python/3.9.4/Python-3.9.4.tar.xz
Installing Python-3.9.4...
Installed Python-3.9.4 to /root/.pyenv/versions/3.9.4
2021-05-23T02:33:27.615Z	INFO	WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
2021-05-23T02:33:27.804Z	ERROR	pyenv: version `WARNING' not installed
2021-05-23T02:33:27.807Z	ERROR	Command exited with 1
2021-05-23T02:33:30.078Z	INFO	* Removed 22 directories under /	{"duration": 2.271}
2021-05-23T02:33:30.220Z	ERROR	failed to execute build plan: execute stage: build stage 0: build node: do execute: execute step: cmd wait: exit status 1
Cleaning up file based variables
00:00
ERROR: Job failed: command terminated with exit code 1
```